name: Test

on:
  pull_request:
  push:

jobs:
  windows:
    name: Windows

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create work drive
        run: 'subst P: test'

      - name: Compile SQF
        uses: ./
        with:
          directory: P:\

      - name: Check SQFC Output
        run: |
          if (!(Test-Path -Path "test/helloworld.sqfc")) {
            throw "Compiled sqfc file not found"
          }
